# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pickupperDelivery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pickupperDelivery
  pod 'Firebase/Core'
  pod 'Firebase/Database'


end

# target 'pickupperDelivery-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for pickupperDelivery-tvOS

#   target 'pickupperDelivery-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
